### ISSUE TITLE
"Upload Integration Flow" uses the technical name for integration flow name

### ISSUE THREAD

**Issue by kfuto** [figaf/cpi-gradle-plugin#9]
Hi,
Firstly, thank you for the work on this plugin!  This is very helpful resource to those of us looking into speeding up our development and or CI/CD processes for CPI.

We name our integration flow's similar to most SAP packages and use spaces to separate words in the name of the integration flow (ex: Replicate Employee from SAP SuccessFactors Employee Central).   When we upload an integration flow via the plugin, the friendly name gets replaced with the technical name of the integration flow (Replicate_Employee_from_SAP_SuccessFactors_Employee _Central).

Can the "Upload Integration Flow" class be updated to allow the integration flow's friendly name to be used for "Name" instead of the technical name?  
`uploadIFlowRequest.setName(integrationFlowTechnicalName);`

The friendly name appears to be available in the MANIFEST.MF file's "Bundle-Name" property.  I think it could be read from this location or set in the Gradle build settings with something like integrationFlowName or integrationFlowFriendlyName.

Thanks,
Kevin

**Comment by NesterovIlya** [comment]
Hello Kevin,

Thank you for your request. Which version of the plugin are you using? The issue with the displayed name was fixed in `1.2.RELEASE` (primary fix) and `1.3.RELEASE` (long name parsing fix):
![image](https://user-images.githubusercontent.com/8762283/83479793-49522980-a4a2-11ea-96a7-08c4d4ec5c75.png)

Please, try to update the version to `1.3.RELEASE` in your `build.gradle` and check upload again.
Let us know if you have any questions.

**Comment by kfuto** [comment]
Thanks!  I was still using the 1.0.RELEASE version.  I can confirm the 1.3 addresses the issue.
